name: Build and deploy to github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - run: |
          mkdir public
          cp -r index.html static/ public/

      # The GITHUB_TOKEN already given for running github actions is not
      # sufficient. It allows me to push to master but for some reason it won't
      # trigger a github-pages "build & push to CDN". I had to create a personal
      # access token with the 'repo' scope. Also, it is not possible anymore to
      # call that secret "GITHUB_PAT".
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./public
          publish_branch: gh-pages
